#!/usr/bin/env python3
"""Draw the cards under .github/assets/.

`hero.png` is the image at the top of README.md: the loop in three columns. The
wordmark and the hook on the left, the files the workspace keeps in the middle,
the seven reviewers on the right. Read left to right it says: here is the claim,
here is what the system holds onto, here is what attacks it. The middle column
is the argument -- every other tool in this category would have an empty one.

`hero-<tag>.png` is the same card in one of the mirror's languages, one per tag
in sync_docs.LANGUAGES, embedded by that language's README. The hero is the only
image in this repository that is mostly words, which is why it is the only one
translated: a reader who arrived in their own language otherwise meets an
English picture first and the translation second. The diagrams under
docs/diagrams/ stay English on every page and move their alt text instead,
because a translated diagram is a per-language render pipeline.

`social.png` is the file uploaded at Settings -> General -> Social preview, and
it is what LinkedIn, Signal, Teams, and Slack actually render when someone pastes
the repository link. It carries the wordmark and the hook and nothing else. It
has no translated twin because a repository has one social preview, and GitHub
picks it without knowing who is looking.

The hero and the social card exist separately because they are read at different
sizes and the same image cannot serve both. An unfurl renders around 400px wide.
At that size the hero's columns collapse into grey texture, and every earlier
attempt to fix that meant deleting detail the README wants. Splitting them ends
the argument: the hero is free to be dense because nobody sees it at 400px, and
the social card is free to be nearly empty because nobody sees it at 1280.

The right column's agents and the bar that groups the blind ones are read from
the review's dispatch table through sync_docs, not typed here. That column is a
diagram of the pipeline's shape, and a diagram of a shape the pipeline no longer
has is worse than no diagram. Every number the cards print is read from the same
place, in every language. The middle column's file list is still typed here,
because it names what onboarding writes rather than anything the tree declares --
so each name is checked against the onboard skill before the card is drawn.

Run after any change to the header text, the file list, or the agent list:

    python3 scripts/make_card.py

Both cards are 1280x640, which is GitHub's social preview size and a clean 2:1.
Anything taller loses its top and bottom edge in a preview.

Needs Pillow. It is not a test dependency, so CI does not run this and no gate
checks the committed PNGs against a fresh render. Pillow encodes the same pixels
differently across versions, so a checksum gate would fail on an unrelated
upgrade. Regenerate by hand and commit the result.

Fonts live in assets/fonts/. All are OFL; the licenses sit beside them. The
Chinese card is set in a subset of Noto Sans CJK SC carrying only the characters
that card draws, regenerated by scripts/subset_cjk_font.py -- so changing a
Chinese string here means running that script too, and this one refuses to draw
until it has been.
"""

import re
import sys
from pathlib import Path
from typing import NamedTuple

from PIL import Image, ImageDraw, ImageFont

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sync_docs  # noqa: E402  -- the dispatch order, read from where it is true

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / "assets" / "fonts"
DEFAULT_DIR = ROOT / ".github" / "assets"

S = 2                      # supersample factor, resized down at the end
W, H = 1280 * S, 640 * S   # GitHub's social preview size, and a clean 2:1 unfurl

# --- palette ---------------------------------------------------------------
# GitHub's dark canvas, so the card sits flush with the README behind it.
CANVAS   = (0x0D, 0x11, 0x17)
RULE     = (0x21, 0x26, 0x2D)
INK      = (0xE6, 0xED, 0xF3)
INK_MUTE = (0x7D, 0x85, 0x90)
INK_BODY = (0xA8, 0xB2, 0xBF)
BLUE     = (0x53, 0x9B, 0xF5)   # the accent: what the card exists to add
BLUE_DIM = (0x31, 0x5C, 0x94)
AMBER    = (0xC6, 0x90, 0x26)

# --- faces -----------------------------------------------------------------
# Saira Condensed and IBM Plex Mono cover Latin, including every Vietnamese
# precomposed vowel and every Spanish and Portuguese accent. Neither has a CJK
# glyph, so the Chinese card is set in a subset of Noto Sans CJK SC instead.
CJK_STEM = "NotoSansCJKsc-Subset"
COVERAGE = FONTS / f"{CJK_STEM}.coverage.txt"
CODEPOINT = re.compile(r"^U\+([0-9A-F]{4,6})", re.MULTILINE)

# Noto ships the subset at two weights against the display face's three, and it
# is drawn a little smaller: a Han glyph fills its em square where a condensed
# Latin letter fills about half of it, so matched point sizes leave the Chinese
# card visibly heavier than the other five.
CJK_WEIGHT = {"Bold": "Bold", "SemiBold": "Bold", "Medium": "Medium"}
CJK_SCALE = 0.86


def disp(size, weight="Bold", script="latin"):
    if script == "cjk":
        return ImageFont.truetype(
            str(FONTS / f"{CJK_STEM}-{CJK_WEIGHT[weight]}.ttf"), int(size * CJK_SCALE * S)
        )
    return ImageFont.truetype(str(FONTS / f"SairaCondensed-{weight}.ttf"), int(size * S))


def mono(size, weight="Regular", script="latin"):
    if script == "cjk":
        return ImageFont.truetype(
            str(FONTS / f"{CJK_STEM}-{CJK_WEIGHT[weight]}.ttf"), int(size * CJK_SCALE * S)
        )
    return ImageFont.truetype(str(FONTS / f"IBMPlexMono-{weight}.ttf"), int(size * S))


def covered() -> set[str]:
    """The characters the vendored CJK subset actually carries.

    A missing glyph does not fail: it draws .notdef, which is a blank or a box,
    and a card of blanks looks like a rendering bug rather than like a string
    somebody edited without re-running the subsetter. So the strings are checked
    against the manifest the subsetter writes before anything is drawn.
    """
    if not COVERAGE.is_file():
        raise SystemExit(
            f"make_card.py: {COVERAGE.relative_to(ROOT)} is missing, so there is "
            f"no way to tell whether the CJK subset covers the Chinese card. "
            f"Run scripts/subset_cjk_font.py."
        )
    text = COVERAGE.read_text(encoding="utf-8")
    return {chr(int(code, 16)) for code in CODEPOINT.findall(text)}


def new_card():
    """A dark canvas with the faint dot grid both cards share."""
    img = Image.new("RGB", (W, H), CANVAS)
    d = ImageDraw.Draw(img)
    for gy in range(0, H, 24 * S):
        for gx in range(0, W, 24 * S):
            d.point((gx, gy), fill=(0x16, 0x1B, 0x22))
    return img, d


def tracked(draw, xy, text, font, fill, track=0):
    """Draw text with letter spacing. Returns the end x."""
    x, y = xy
    for ch in text:
        draw.text((x, y), ch, font=font, fill=fill)
        x += draw.textlength(ch, font=font) + track * S
    return x


def tracked_len(draw, text, font, track=0):
    return sum(draw.textlength(c, font=font) + track * S for c in text)


PAD = 72 * S
FOOT_GUTTER = 32 * S       # clear space between the footer's two anchored runs
URL = "github.com/VonTerraProject501c3/slushpile"

# Drawn as separate runs so the second half carries the accent. Kept here rather
# than inline in each card, because a wordmark that differs between the README
# image and the link preview looks like two different projects.
WORDMARK = (("slush", INK), ("pile", BLUE))

# The workspace files the middle column shows. The names are the same in every
# language -- they are filenames on the reader's disk, not prose -- so only the
# captions beside them are translated, in each Card below.
FILES = ("profile.md", "preferences.yaml", "stories.md", "job_search.md")

# Workspace files onboarding writes that the middle column leaves out, with the
# reason. Four rows is what fits above the caption at this type size, so the
# omission is a layout decision — recorded here so it reads as one, rather than
# as a file nobody noticed. The guard in check_workspace refuses to draw when a
# fifth file appears in the workspace and lands in neither list.
OMITTED = {
    "companies.md": "one line per company ever looked at — the least "
                    "load-bearing of the five, and the column holds four",
}

# Onboarding's Phase 6 scaffold block, and the workspace files inside it.
SCAFFOLD_BLOCK = re.compile(r"Create the directory structure:\s*```(.*?)```", re.DOTALL)
WORKSPACE_FILE = re.compile(r"^([\w.-]+\.(?:md|yaml))", re.MULTILINE)


class Card(NamedTuple):
    """Every string one language's hero draws, and how to set them.

    Each field is a line, or a tuple of lines, rather than a paragraph the
    drawing code wraps. Wrapping would be one algorithm serving five scripts
    with different word lengths and no shared idea of where a line may break,
    and it would move the decision about what the card emphasises away from
    whoever wrote the words. The columns are narrow; every break is a choice.

    `{n}`, `{n_word}`, `{N_WORD}`, `{blind}`, `{blind_word}` and `{Blind_word}`
    are filled from the review's dispatch table. A number typed here is a number
    that goes stale the next time the pipeline's shape changes, which is the one
    kind of error a picture hides best.

    English prose spells a small number out; the mirror writes it as a digit,
    on the same rule the translated pages follow, so that a count stays
    matchable in a language whose number words nothing here knows.
    """

    eyebrow: str
    hook: tuple[str, ...]          # the claim, in body colour
    keep: tuple[str, ...]          # the line the card exists to add, in accent
    keep_label: str
    captions: tuple[str, ...]      # one per FILES row, in order
    keep_note: tuple[str, ...]
    reviewers_label: str
    reviewers: dict[str, str]      # dispatch name (English) -> what to print
    blind_note: tuple[str, ...]
    script: str = "latin"
    # English prints the reviewers as lowercase mono, the way the repository
    # names them: they are identifiers there, and the column reads as a list of
    # agents. Translated, they are descriptions rather than names, and the
    # longest of them is half again the column's width in a monospace face. The
    # condensed display face fits them and stops implying they are strings a
    # user types.
    mono_reviewers: bool = False


CARDS = {
    "en": Card(
        eyebrow="AN ADVERSARIAL JOB SEARCH WITH A MEMORY",
        hook=("Seven agents try to reject you", "before a recruiter gets the chance."),
        keep=("What they find, you keep.",),
        keep_label="WHAT YOU KEEP",
        captions=(
            "every factual claim",
            "comp, location, constraints",
            "four to eight, tellable",
            "outcomes, for calibration",
        ),
        keep_note=("Written once. Read by every", "stage. Updated by every review."),
        reviewers_label="THE {N_WORD} REVIEWERS",
        reviewers={
            "triage screener": "triage screener",
            "requirements analyst": "requirements analyst",
            "ats simulator": "ats simulator",
            "fatigued reader": "fatigued reader",
            "pool analyst": "pool analyst",
            "hiring manager": "hiring manager",
            "contrarian": "contrarian",
        },
        blind_note=(
            "{Blind_word} in parallel, blind to each",
            "other. Then synthesis. Then an",
            "agent whose job is overturning it.",
        ),
        mono_reviewers=True,
    ),
    "zh-CN": Card(
        eyebrow="一场有记忆的对抗式求职",
        hook=("{n} 个智能体抢在招聘人员", "之前把你拒掉。"),
        keep=("它们发现的东西，归你。",),
        keep_label="你留下的",
        captions=(
            "每一条事实性主张",
            "薪酬、地点、约束条件",
            "四到八个，讲得出口",
            "结果，用于校准",
        ),
        keep_note=("写一次。每个阶段都读它。", "每次审阅都更新它。"),
        reviewers_label="{n} 个审阅者",
        reviewers={
            "triage screener": "初筛者",
            "requirements analyst": "需求分析师",
            "ats simulator": "ATS 模拟器",
            "fatigued reader": "疲惫的读者",
            "pool analyst": "申请者池分析师",
            "hiring manager": "招聘经理",
            "contrarian": "唱反调者",
        },
        blind_note=(
            "其中 {blind} 个并行审阅者彼此盲评。",
            "然后是综合。然后是一个",
            "专职推翻结论的智能体。",
        ),
        script="cjk",
    ),
    "es": Card(
        eyebrow="UNA BÚSQUEDA DE EMPLEO ADVERSARIAL CON MEMORIA",
        hook=("{n} agentes intentan rechazarte", "antes de que lo haga un reclutador."),
        keep=("Lo que encuentran, te lo quedas.",),
        keep_label="LO QUE TE QUEDAS",
        captions=(
            "cada afirmación factual",
            "sueldo, ubicación, límites",
            "de cuatro a ocho, contables",
            "resultados, para calibrar",
        ),
        keep_note=("Se escribe una vez. Lo lee cada", "etapa. Lo actualiza cada revisión."),
        reviewers_label="LOS {n} REVISORES",
        reviewers={
            "triage screener": "filtro de triaje",
            "requirements analyst": "analista de requisitos",
            "ats simulator": "simulador ATS",
            "fatigued reader": "lector fatigado",
            "pool analyst": "analista del pool",
            "hiring manager": "hiring manager",
            "contrarian": "contrarian",
        },
        blind_note=(
            "{blind} revisores en paralelo, ciegos",
            "entre sí. Luego la síntesis. Luego",
            "un agente que intenta revocarla.",
        ),
    ),
    "pt-BR": Card(
        eyebrow="UMA BUSCA DE EMPREGO ADVERSARIAL COM MEMÓRIA",
        hook=("{n} agentes tentam rejeitar você", "antes que um recrutador consiga."),
        keep=("O que encontram, fica com você.",),
        keep_label="O QUE FICA COM VOCÊ",
        captions=(
            "cada afirmação factual",
            "remuneração, local, restrições",
            "de quatro a oito, contáveis",
            "resultados, para calibração",
        ),
        keep_note=("Escrito uma vez. Lido por toda", "etapa. Atualizado por toda revisão."),
        reviewers_label="OS {n} REVISORES",
        reviewers={
            "triage screener": "triador",
            "requirements analyst": "analista de requisitos",
            "ats simulator": "simulador de ATS",
            "fatigued reader": "leitor cansado",
            "pool analyst": "analista do pool",
            "hiring manager": "gestor da vaga",
            "contrarian": "contrarian",
        },
        blind_note=(
            "{blind} revisores em paralelo, cegos uns",
            "aos outros. Depois a síntese. Depois",
            "um agente que tenta derrubá-la.",
        ),
    ),
    "en-x-aibro": Card(
        eyebrow="CONTEXT ENGINEERING FOR CANDIDATE-MARKET FIT",
        hook=("{n} agents try to reject you", "before a recruiter gets the chance."),
        keep=("What they find, you keep.",),
        keep_label="THE MEMORY LAYER",
        captions=(
            "single source of truth",
            "your constraint vector",
            "four to eight, high-signal",
            "the outcome ledger",
        ),
        keep_note=("Written once. Read by every stage.", "Compounding, not stateless."),
        reviewers_label="THE {n}-AGENT ENSEMBLE",
        reviewers={
            "triage screener": "top-of-funnel filter",
            "requirements analyst": "requirements parser",
            "ats simulator": "ATS parse simulation",
            "fatigued reader": "attention-decay reader",
            "pool analyst": "comparative pool ranker",
            "hiring manager": "hiring-manager persona",
            "contrarian": "kill-authority contrarian",
        },
        blind_note=(
            "{blind} dispatched in parallel, blind.",
            "Then synthesis. Then an agent with",
            "kill authority over the pipeline.",
        ),
    ),
    "vi": Card(
        eyebrow="MỘT CUỘC TÌM VIỆC ĐỐI KHÁNG CÓ TRÍ NHỚ",
        hook=("{n} tác nhân cố loại bạn trước khi", "một nhà tuyển dụng kịp làm vậy."),
        keep=("Những gì chúng tìm ra, bạn giữ lại.",),
        keep_label="NHỮNG GÌ BẠN GIỮ LẠI",
        captions=(
            "mọi tuyên bố sự kiện",
            "lương, địa điểm, ràng buộc",
            "bốn đến tám, kể được",
            "kết quả, để hiệu chỉnh",
        ),
        keep_note=("Viết một lần. Mọi giai đoạn đều đọc.", "Mọi vòng đánh giá đều cập nhật."),
        reviewers_label="{n} NGƯỜI ĐÁNH GIÁ",
        reviewers={
            "triage screener": "người sàng lọc nhanh",
            "requirements analyst": "phân tích yêu cầu",
            "ats simulator": "trình mô phỏng ATS",
            "fatigued reader": "người đọc đã mệt",
            "pool analyst": "phân tích nhóm ứng viên",
            "hiring manager": "quản lý tuyển dụng",
            "contrarian": "người phản biện",
        },
        blind_note=(
            "{blind} người đánh giá song song, mù",
            "với nhau. Rồi tổng hợp. Rồi một tác",
            "nhân có nhiệm vụ lật ngược kết quả.",
        ),
    ),
}


def draw_wordmark(d, x, y, font):
    for part, colour in WORDMARK:
        d.text((x, y), part, font=font, fill=colour)
        x += d.textlength(part, font=font)


def centred(draw, y, text, font, fill):
    draw.text(((W - draw.textlength(text, font=font)) / 2, y), text, font=font, fill=fill)


def check_languages() -> None:
    """Every language in the mirror gets a card, or this stops.

    A language added to sync_docs.LANGUAGES without a Card here would otherwise
    keep embedding the English hero, which is the one failure a translated page
    cannot show: the picture is fine, it is just somebody else's.
    """
    wanted = {language.tag for language in sync_docs.LANGUAGES}
    have = set(CARDS) - {"en"}
    if wanted != have:
        raise SystemExit(
            f"make_card.py: the mirror carries {sorted(wanted)} and CARDS covers "
            f"{sorted(have)}. Missing: {sorted(wanted - have) or 'none'}. "
            f"Unknown: {sorted(have - wanted) or 'none'}."
        )


def check_workspace() -> None:
    """FILES must be exactly the workspace, in both directions."""
    onboard = (ROOT / "skills" / "onboard" / "SKILL.md").read_text(encoding="utf-8")

    # A file the card claims the workspace keeps, that onboarding never writes,
    # is the card being wrong about the one thing it exists to claim.
    unwritten = [name for name in FILES if name not in onboard]
    if unwritten:
        raise SystemExit(
            f"make_card.py: the workspace column names {', '.join(unwritten)}, "
            f"which skills/onboard/SKILL.md never writes"
        )

    # And the other direction, which is the one that was open. The check above
    # catches a deleted file; it cannot catch a file added to the workspace and
    # never added here, which leaves the column quietly short on the one claim
    # the card exists to make.
    block = SCAFFOLD_BLOCK.search(onboard)
    if not block:
        raise SystemExit(
            "make_card.py: skills/onboard/SKILL.md no longer has the scaffold "
            "block this column is checked against. Restore it, or point "
            "SCAFFOLD_BLOCK at wherever the workspace file list moved."
        )
    unaccounted = sorted(
        set(WORKSPACE_FILE.findall(block.group(1))) - set(FILES) - set(OMITTED)
    )
    if unaccounted:
        raise SystemExit(
            f"make_card.py: onboarding writes {', '.join(unaccounted)}, which the "
            f"workspace column neither shows nor records as a deliberate "
            f"omission. Add it to FILES, or to OMITTED with the reason."
        )


def resolve(tag: str, facts: sync_docs.Facts) -> Card:
    """One language's Card with its counts filled in and its shape checked."""
    card = CARDS[tag]
    blind = len(facts.blind)
    numbers = {
        "n": len(facts.dispatch),
        "n_word": sync_docs.spell(len(facts.dispatch)),
        "N_WORD": sync_docs.spell(len(facts.dispatch)).upper(),
        "blind": blind,
        "blind_word": sync_docs.spell(blind),
        "Blind_word": sync_docs.spell(blind).capitalize(),
    }

    dispatch = [sync_docs.plain(name) for name in facts.dispatch]
    if set(dispatch) != set(card.reviewers):
        raise SystemExit(
            f"make_card.py: the {tag} card labels {sorted(card.reviewers)}, and "
            f"the review dispatches {sorted(dispatch)}. A renamed agent needs a "
            f"label in every language, or its column silently shifts by one."
        )
    if len(card.captions) != len(FILES):
        raise SystemExit(
            f"make_card.py: the {tag} card has {len(card.captions)} captions for "
            f"{len(FILES)} workspace files"
        )

    if card.script == "cjk":
        strings = [card.eyebrow, card.keep_label, card.reviewers_label,
                   *card.hook, *card.keep, *card.captions, *card.keep_note,
                   *card.blind_note, *card.reviewers.values()]
        missing = sorted({c for s in strings for c in s.format(**numbers)} - covered())
        if missing:
            raise SystemExit(
                f"make_card.py: the {tag} card draws {''.join(missing)}, which the "
                f"vendored subset does not carry. Run scripts/subset_cjk_font.py "
                f"and commit both faces with the card."
            )

    fill = lambda text: text.format(**numbers)  # noqa: E731
    return card._replace(
        eyebrow=fill(card.eyebrow),
        hook=tuple(fill(line) for line in card.hook),
        keep=tuple(fill(line) for line in card.keep),
        keep_label=fill(card.keep_label),
        keep_note=tuple(fill(line) for line in card.keep_note),
        reviewers_label=fill(card.reviewers_label),
        blind_note=tuple(fill(line) for line in card.blind_note),
    )


class Overflow:
    """Collects every line that runs past its column, and reports them together.

    A card that overflows is not subtly wrong: text crosses the hairline into
    the next column and the three-column structure the whole design rests on
    stops reading. Nothing about the drawing code can prevent it, because the
    words are written by hand in five languages and a Spanish sentence is
    reliably a third longer than the English one it translates.

    Failing on the first one would mean five runs to tune five lines, so they
    are gathered and raised at once.
    """

    def __init__(self, label: str) -> None:
        self.label = label
        self.problems: list[str] = []

    def wide(self, draw, text, font, right, where, x=0, track=0):
        over = (x + tracked_len(draw, text, font, track)) - right
        if over > 0:
            self.problems.append(f"{where}: {text!r} runs {over / S:.0f}px past its column")

    def tall(self, lines, top, step, floor, where):
        over = (top + len(lines) * step) - floor
        if over > 0:
            self.problems.append(
                f"{where}: {len(lines)} lines run {over / S:.0f}px past the space for them"
            )

    def raise_if_any(self) -> None:
        if self.problems:
            joined = "\n  ".join(self.problems)
            raise SystemExit(
                f"make_card.py: the {self.label} does not fit:\n  {joined}\n"
                f"Shorten the line or break it differently in CARDS. The columns "
                f"are fixed: whatever spills crosses into the next one."
            )


def fitted_track(draw, text, font, width, track):
    """The requested letter spacing, or the most of it that fits.

    Only the three column headings are tracked, and only they use this. Tracking
    is the one thing on the card that can absorb a longer translation without
    anyone noticing, so it gives way before the type size does.
    """
    while track > 0 and tracked_len(draw, text, font, track) > width:
        track -= 0.25
    return track


def draw_hero(d, tag: str, card: Card, facts: sync_docs.Facts):
    """A README's header image: the loop in three columns."""
    COL_M, COL_R = 580 * S, 902 * S     # middle and right column left edges
    LABEL_Y, LIST_Y, NOTE_Y = 52 * S, 104 * S, 448 * S
    HOOK_Y, HOOK_STEP = 272 * S, 40 * S
    NOTE_STEP = 26 * S
    RULES = (540 * S, 862 * S)          # the two hairlines, and the column edges
    GUTTER = 20 * S
    FOOT = 552 * S                      # the notes stop clear of the footer rule
    script = card.script

    label_font = disp(20, "SemiBold", script)
    note_font = disp(20, "Medium", script)
    over = Overflow(f"{tag} hero")

    # Two hairlines carry the three-column structure. Without them the middle and
    # right lists read as one ragged block of grey text.
    for x in RULES:
        d.rectangle([x, 44 * S, x + 1, 524 * S], fill=RULE)

    # --- left: the wordmark and the hook, verbatim from that language's README --
    track = fitted_track(d, card.eyebrow, label_font, RULES[0] - GUTTER - PAD, 2.5)
    tracked(d, (PAD, LABEL_Y), card.eyebrow, label_font, INK_MUTE, track=track)
    over.wide(d, card.eyebrow, label_font, RULES[0] - GUTTER, "eyebrow", x=PAD, track=track)

    # Sized to clear the x=540 hairline: nine mono characters at 80px is 432px
    # from a 72px margin, which leaves the column its gutter. The wordmark is a
    # name, so it is Latin on every card.
    draw_wordmark(d, PAD, 104 * S, mono(80, "Medium"))

    # The last line is the one the card exists to add, so it carries the accent.
    # In body colour it reads as a trailing clause and gets skipped at small sizes.
    tag_font = disp(36, "Medium", script)
    lines = [(line, INK_BODY) for line in card.hook] + [(line, BLUE) for line in card.keep]
    over.tall(lines, HOOK_Y, HOOK_STEP, 524 * S, "hook")
    for i, (line, colour) in enumerate(lines):
        d.text((PAD, HOOK_Y + i * HOOK_STEP), line, font=tag_font, fill=colour)
        over.wide(d, line, tag_font, RULES[0] - GUTTER, "hook", x=PAD)

    # ===========================================================================
    # Middle: the durable workspace. These are the files onboard writes and every
    # later skill reads. Adding a file to the workspace without adding it here
    # leaves the card quietly wrong.
    # ===========================================================================
    track = fitted_track(d, card.keep_label, label_font, RULES[1] - GUTTER - COL_M, 2.5)
    tracked(d, (COL_M, LABEL_Y), card.keep_label, label_font, INK_MUTE, track=track)
    over.wide(d, card.keep_label, label_font, RULES[1] - GUTTER, "keep label", x=COL_M, track=track)

    # The filenames stay mono and stay English: they are paths on the reader's
    # disk, and a translated one would be a file that does not exist.
    file_font = mono(22, "Medium")
    caption_font = disp(21, "Medium", script)
    for i, (name, caption) in enumerate(zip(FILES, card.captions)):
        y = LIST_Y + i * 72 * S
        d.rectangle([COL_M, y + 4 * S, COL_M + 3 * S, y + 24 * S], fill=BLUE_DIM)
        d.text((COL_M + 16 * S, y), name, font=file_font, fill=INK)
        d.text((COL_M + 16 * S, y + 32 * S), caption, font=caption_font, fill=INK_MUTE)
        over.wide(d, caption, caption_font, RULES[1] - GUTTER, "caption", x=COL_M + 16 * S)

    over.tall(card.keep_note, NOTE_Y, NOTE_STEP, FOOT, "workspace note")
    for i, line in enumerate(card.keep_note):
        d.text((COL_M, NOTE_Y + i * NOTE_STEP), line, font=note_font, fill=INK_MUTE)
        over.wide(d, line, note_font, RULES[1] - GUTTER, "workspace note", x=COL_M)

    # ===========================================================================
    # Right: the reviewers, in dispatch order. The bracket is the architecture --
    # the blind ones run concurrently and cannot see each other's findings, which
    # is the whole reason their agreement counts as evidence.
    # ===========================================================================
    blind = len(facts.blind)  # 1..blind run concurrently; then synthesis, then falsification
    labels = [card.reviewers[sync_docs.plain(name)] for name in facts.dispatch]

    track = fitted_track(d, card.reviewers_label, label_font, W - PAD - COL_R, 2.5)
    tracked(d, (COL_R, LABEL_Y), card.reviewers_label, label_font, INK_MUTE, track=track)
    over.wide(d, card.reviewers_label, label_font, W - PAD, "reviewers label", x=COL_R, track=track)

    agent_font = mono(20, "Medium") if card.mono_reviewers else disp(22, "Medium", script)
    rows = [LIST_Y + i * 48 * S for i in range(len(labels))]
    for y, name in zip(rows, labels):
        d.text((COL_R + 16 * S, y), name, font=agent_font, fill=INK_BODY)
        over.wide(d, name, agent_font, W - PAD, "reviewer", x=COL_R + 16 * S)

    # One bar spanning the parallel stages, then a bar each for the two that run
    # alone. The grouping is the claim; the colour change marks the new job.
    d.rectangle([COL_R, rows[0] + 4 * S, COL_R + 3 * S, rows[blind - 1] + 24 * S], fill=BLUE_DIM)
    d.rectangle([COL_R, rows[blind] + 4 * S, COL_R + 3 * S, rows[blind] + 24 * S], fill=AMBER)
    d.rectangle(
        [COL_R, rows[blind + 1] + 4 * S, COL_R + 3 * S, rows[blind + 1] + 24 * S], fill=BLUE
    )

    over.tall(card.blind_note, NOTE_Y, NOTE_STEP, FOOT, "review note")
    for i, line in enumerate(card.blind_note):
        d.text((COL_R, NOTE_Y + i * NOTE_STEP), line, font=note_font, fill=INK_MUTE)
        over.wide(d, line, note_font, W - PAD, "review note", x=COL_R)

    # --- footer ----------------------------------------------------------------
    # The hairline is load-bearing. Without it the URL reads as a fifth line of the
    # left column rather than as the card's footer.
    d.rectangle([PAD, 562 * S, W - PAD, 562 * S + 1], fill=RULE)

    # Both lines sit on one baseline. The two faces have different ascents, so a
    # shared top edge would leave them visibly off by a few pixels. Neither is
    # translated: one is a URL and the other is four product names.
    BASE = H - 44 * S
    url_font = mono(23, "Medium")
    harnesses = "CLAUDE CODE  ·  CODEX  ·  CURSOR  ·  GEMINI CLI"
    hf = disp(21, "SemiBold")
    harness_left = W - PAD - tracked_len(d, harnesses, hf, track=2.5)

    # The only row whose neighbour moves: URL anchored left, harnesses right.
    # Every other guard measures against a fixed column, so this one has to be
    # written separately or the URL grows into the harness list with no error.
    over.wide(d, URL, url_font, harness_left - FOOT_GUTTER, "footer URL", x=PAD)

    d.text((PAD, BASE - url_font.getmetrics()[0]), URL, font=url_font, fill=INK_MUTE)
    tracked(d, (harness_left, BASE - hf.getmetrics()[0]),
            harnesses, hf, (0x6E, 0x73, 0x7B), track=2.5)

    return over


def draw_social(d, card: Card):
    """The unfurl card. Read at ~400px wide, so it holds the hook and nothing else.

    Everything here is set two to three times larger than the same text on the
    hero. A 42px line survives the scale down to roughly 13px; the hero's 20px
    list items would land at 6px, which is why none of them are here.
    """
    # Everything here is centred, so a line that is too long bleeds off both
    # edges rather than into a column. Measured against the same margin the hero
    # uses, since a card cropped at 400px has no room to lose a character.
    over = Overflow("social card")

    eyebrow = disp(26, "SemiBold")
    over.wide(d, card.eyebrow, eyebrow, W - 2 * PAD, "eyebrow", track=4)
    tracked(d, ((W - tracked_len(d, card.eyebrow, eyebrow, track=4)) / 2, 138 * S),
            card.eyebrow, eyebrow, INK_MUTE, track=4)

    # Centred, so the whole wordmark is measured before it is placed.
    wordmark = mono(124, "Medium")
    total = sum(d.textlength(p, font=wordmark) for p, _ in WORDMARK)
    draw_wordmark(d, (W - total) / 2, 190 * S, wordmark)

    tag_font = disp(42, "Medium")
    for i, line in enumerate([*card.hook, *card.keep]):
        over.wide(d, line, tag_font, W - 2 * PAD, "hook line")
        centred(d, (396 + i * 48) * S, line, tag_font,
                BLUE if line in card.keep else INK_BODY)

    url_font = mono(21, "Medium")
    over.wide(d, URL, url_font, W - 2 * PAD, "URL")
    centred(d, 570 * S, URL, url_font, (0x5C, 0x63, 0x6D))

    return over


def main():
    out_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DIR
    check_languages()
    check_workspace()
    facts = sync_docs.Facts()

    for tag in CARDS:
        card = resolve(tag, facts)
        img, d = new_card()
        draw_hero(d, tag, card, facts).raise_if_any()
        name = "hero.png" if tag == "en" else f"hero-{tag}.png"
        out = img.resize((W // S, H // S), Image.LANCZOS)
        out.save(out_dir / name, optimize=True)
        print(f"wrote {out_dir / name} {out.size[0]}x{out.size[1]}")

    img, d = new_card()
    draw_social(d, resolve("en", facts)).raise_if_any()
    out = img.resize((W // S, H // S), Image.LANCZOS)
    out.save(out_dir / "social.png", optimize=True)
    print(f"wrote {out_dir / 'social.png'} {out.size[0]}x{out.size[1]}")


if __name__ == "__main__":
    main()
