#!/usr/bin/env python3
"""Generate every derived documentation file from its canonical source.

Several surfaces describe this pipeline to a reader or to another model:
CLAUDE.md and its AGENTS.md mirror, the two Cursor router files, GEMINI.md,
README.md, the paste-in snippet in INSTALL.md, and the docs/ tree. Every one of
them lists the skills, and most of them state the review's shape. None of those facts is theirs to hold. They
live in `skills/`, in `agents/`, and in the dispatch table inside
`skills/adversarial-review/SKILL.md`.

A list that drifts is not a cosmetic problem. A skill missing from the Cursor
router is a stage a Cursor user cannot reach, and a reviewer reading a diff has
no way to see it. So the lists are generated, and the prose around them lives
here.

Three kinds of generated output:

**Whole files.** AGENTS.md mirrors CLAUDE.md. The two Cursor files are built
from the tree, with their framing prose in this script.

**Marked regions.** README.md, INSTALL.md, and GEMINI.md are hand-written except
between `BEGIN GENERATED` and `END GENERATED` markers. Anything inside a marked
region is overwritten on the next run.

**Count claims.** A few sentences state a number in prose, where a marked region
would be heavier than the sentence it wraps. Those are checked, not written: the
sentence must appear with the right number in it, or this script fails and names
the file.

A registered claim only covers the sentence someone thought to register, which
is the weaker half of the problem: "eight skills" sat in INSTALL.md, in the help
skill, and in the marketplace manifest through the ninth skill shipping, because
no row named those sentences. So a sweep runs alongside the claims and reads
every shipped surface for a counted noun — "nine skills", "eight agents",
"seven reviewers" — and fails on any number that is not a true count, whether or
not a row names it. The claims pin the wording of the sentences that matter; the
sweep catches the ones nobody registered.

Everything derived is looked up by name, and a name that matches nothing is an
error rather than a silent omission. That is the point. Add a skill, forget the
router, and this fails instead of shipping a pipeline with an unreachable stage.

    python3 scripts/sync_docs.py            # write the derived copies
    python3 scripts/sync_docs.py --check    # exit 1 if a copy has drifted

--check is the CI gate. A pull request that edits CLAUDE.md, adds a skill, or
reorders the review pipeline without running the generator fails there rather
than shipping files that disagree.
"""

from __future__ import annotations

import argparse
import posixpath
import re
import sys
import textwrap
from pathlib import Path
from typing import Callable, NamedTuple

ROOT = Path(__file__).resolve().parents[1]

MARKER = "<!-- Generated by scripts/sync_docs.py. Do not edit this file. -->"


def begin(region: str) -> str:
    return f"<!-- BEGIN GENERATED {region}: scripts/sync_docs.py -->"


def end(region: str) -> str:
    return f"<!-- END GENERATED {region} -->"


# The dispatch table that fixes the review pipeline's shape. Its rows are the
# source of truth for the order the personas run in and for how many run blind.
DISPATCH_SOURCE = "skills/adversarial-review/SKILL.md"

DISPATCH_ROW = re.compile(
    r"^\|\s*(\d+)\s*\|\s*`(slushpile-[a-z0-9-]+)`\s*\|([^|]*)\|([^|]*)\|"
)

# The dispatch table names a model per agent and so does each agent's
# frontmatter. Only the frontmatter governs what a harness actually dispatches;
# the column is documentation. They are read together below so the documentation
# cannot quietly describe a pipeline that runs on different models.
FRONTMATTER_BLOCK = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
MODEL_FIELD = re.compile(r"^model:\s*(\S+)\s*$", re.MULTILINE)

# Prose reads "seven agents", not "7 agents". Anything past this falls back to
# digits, which is wrong-looking enough to notice.
NUMBER_WORDS = {
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve",
}


class Skill(NamedTuple):
    """One skill, and how each surface names it.

    Four surfaces, four voices: the Cursor skill router, the shorter always-on
    Cursor rule, the README's command list, and the snippet INSTALL.md tells a
    user to paste. They are separate fields rather than one label because they
    are read in different places at different lengths, and collapsing them would
    make every surface read like the least specific one.

    `rule` may be None, which keeps the skill out of the always-on rule. That is
    a decision recorded here, not an omission nobody notices.

    `runs` names the skills this one dispatches on the user's behalf, and it is
    declared rather than grepped out of the prose. A skill file names another
    skill for two different reasons — "run this next" and "this is your
    prerequisite" — and only the first is a call. Grepping would read
    application-builder's pointer back at job-board-search as the pipeline
    running backwards. What is declared here is then verified against the file.

    `anytime` marks a skill that is neither a pipeline stage nor called by one.
    Without it such a skill falls into the spine by default and the README tells
    the user to run it in sequence, which is wrong for anything advisory.

    Any label may use {agents}/{Agents} and {blind}/{Blind}: the number of review
    personas, and how many of them run blind, spelled out.
    """

    name: str
    cursor: str
    rule: str | None
    readme: tuple[str, ...]
    install: str
    runs: tuple[str, ...] = ()
    anytime: bool = False


# Pipeline order: the order a user runs them. Every skill on disk must appear
# here exactly once. README blurbs are pre-wrapped because their column is
# narrow and a machine-chosen break lands in worse places than a human's.
SKILLS = (
    Skill(
        name="onboard",
        cursor="Set up a workspace, first time",
        rule="Set up the workspace, once",
        readme=("once per workspace — builds your profile,", "preferences, and stories"),
        install="set up the workspace, once",
    ),
    Skill(
        name="job-board-search",
        cursor="Search a company's careers board",
        rule="Search and score roles",
        readme=(
            "search a careers board, extract postings,",
            "score pool-anchored fit, contrarian gate,",
            "create role folders",
        ),
        install="search and score roles",
    ),
    Skill(
        name="explore-experience",
        cursor="Surface experience they never wrote down",
        rule="Interview for undocumented experience",
        readme=("interview to surface experience you have", "but never wrote down"),
        install="interview for undocumented experience",
    ),
    Skill(
        name="application-builder",
        cursor="Build a resume and cover letter for a role",
        rule="Build a resume and cover letter",
        readme=(
            "build the resume and cover letter, then",
            "iterate them against the review until they",
            "stabilize",
        ),
        install="build the resume and cover letter",
        runs=("explore-experience", "adversarial-review", "removing-ai-tells"),
    ),
    Skill(
        name="adversarial-review",
        cursor="Review materials before submitting",
        rule="{Agents}-agent adversarial review",
        readme=("{agents} agents, {blind} in parallel, verdict", "per channel"),
        install="run the {agents}-agent review",
    ),
    Skill(
        name="removing-ai-tells",
        cursor="Strip AI tells from prose",
        rule=None,
        readme=(
            "strip AI-authorship signals from prose,",
            "with a gatekeeper on every change",
        ),
        install="strip AI-authorship signals from prose",
    ),
    Skill(
        name="redesign-templates",
        cursor="Redesign the resume and letter templates",
        rule="Restyle the document templates",
        readme=(
            "restyle the resume and letter templates,",
            "holding the ATS constraints fixed",
        ),
        install="restyle the document templates",
        anytime=True,
    ),
    Skill(
        name="status",
        cursor="Report on the search and check its calibration",
        rule="Report search state and calibration",
        readme=(
            "the queue, what is waiting on you, and whether",
            "the pipeline's predictions are holding up",
        ),
        install="report the queue and check pipeline calibration",
        anytime=True,
    ),
    Skill(
        name="help",
        cursor="Ask how any of this works",
        rule=None,
        readme=("what to run next, and how to read the output",),
        install="what to run next, and how to read the output",
        anytime=True,
    ),
)

# What each persona simulates, for the README table. Keyed by agent name so a
# renamed agent fails here rather than leaving the table describing someone who
# no longer exists. Display names come from the file stem; only initialisms need
# an override.
AGENT_DISPLAY = {"slushpile-ats-simulator": "ATS simulator"}

REVIEWERS = {
    "slushpile-triage-screener": "11 seconds, F-pattern, 347 resumes already read today",
    "slushpile-requirements-analyst": (
        "30 seconds, methodical, checks every qualification against evidence"
    ),
    "slushpile-ats-simulator": (
        "A parser. Not a reader. Structure, keywords, and years-of-experience math"
    ),
    "slushpile-fatigued-reader": (
        "Application #61 of 80. What annoys, what gets skimmed, what closes the tab"
    ),
    "slushpile-pool-analyst": "A recruiter who knows what the queue actually looks like",
    "slushpile-hiring-manager": (
        "The person who has to justify the interview slot to their skip-level"
    ),
    "slushpile-contrarian": "Whoever should have asked whether any of this was worth doing",
}

# Sentences that state a derived number in prose, where a marked region would be
# heavier than the sentence it wraps. Checked, not written: the formatted text
# must appear verbatim in the file. Rewording one means updating it here, which
# is the prompt to check whether the number is still right.
COUNT_CLAIMS = (
    ("CLAUDE.md", "{Skills} skills and {defined} agent definitions are the product."),
    ("GEMINI.md", "{Skills} skills and {defined}\nagents that take a role"),
    ("README.md", "An {ordinal_agents} agent writes the cover letter."),
    ("README.md", "The {skills} skills and {defined} agents are Markdown."),
    ("CONTRIBUTING.md", "The {skills} skills and {defined} agents are Markdown"),
    ("INSTALL.md", "slushpile is {skills} skills and {defined} agent definitions"),
)

# Hand-written surfaces that must name every skill as a runnable command.
# Generation covers the Cursor router, the README's command list, and the
# INSTALL snippet. This covers the rosters a person types out, which is where
# the omissions actually happen: the help skill listed eight of the nine for as
# long as there have been nine, and it is the surface whose entire job is
# answering "what do I run next", so the missing one was unreachable from the
# only place a confused user looks.
COMMAND_ROSTERS = ("skills/help/SKILL.md", "docs/skills.md")

# --- the sweep ---------------------------------------------------------------

# Counted nouns, and which derived totals are true of each. A bare "agents" is
# genuinely ambiguous in this product's prose — seven run the review, eight
# ship — so both numbers pass and only a third is an error. "reviewers" and
# "personas" name the dispatched set and nothing else, so they are strict.
#
# The "specialist" forms count the blind stage rather than the whole pipeline.
# They are here because that number is spelled out across six hand-written
# files, and until it was swept the only thing pinning it was a literal in
# tests/test_structure.py — which fails with the number and none of the files,
# so the cheapest way to make the suite green is to edit the literal and ship
# the stale prose.
COUNTED_NOUNS = {
    "skills": ("skills",),
    "skill files": ("skills",),
    "agents": ("dispatch", "shipped"),
    "agent definitions": ("shipped",),
    "reviewers": ("dispatch",),
    "personas": ("dispatch",),
    "specialists": ("blind",),
    "specialist reports": ("blind",),
    "specialist reviewers": ("blind",),
    "specialist stages": ("blind",),
}

# Multi-word nouns join on \s+ rather than a literal space: these files are
# hard-wrapped at 80 columns, so "five specialist\nreports" is ordinary and a
# literal space would read straight past it.
COUNTED_PHRASE = re.compile(
    r"\b(" + "|".join(NUMBER_WORDS.values()) + r")[\s-]+"
    r"(skill\s+files|skills|agent\s+definitions|agents|reviewers|personas"
    r"|specialist\s+reports|specialist\s+reviewers|specialist\s+stages"
    r"|specialists)\b",
    re.IGNORECASE,
)

# The blind count again, in the shapes that put a verb or a connective between
# the number and the noun: "five of whom run in parallel", "the first five are
# supposed to be blind", "five parallel ones". A rule loose enough to catch
# those from the noun alone also catches "three parallel phrases" in a voice
# agent's style notes, so the connectives are whitelisted instead of skipped.
BLIND_PHRASE = re.compile(
    r"\b(" + "|".join(NUMBER_WORDS.values()) + r")\b"
    r"(?:\s+of\s+(?:them|whom|these))?"
    r"(?:\s+(?:run|ran|are|is))?"
    r"(?:\s+supposed\s+to\s+be)?"
    r"\s+(in\s+parallel|blind|parallel\s+(?:review\s+)?(?:ones|stages))\b",
    re.IGNORECASE,
)

# Every shape BLIND_PHRASE's second group can take, whitespace-normalized.
BLIND_NOUNS = {
    "in parallel": ("blind",),
    "blind": ("blind",),
    "parallel ones": ("blind",),
    "parallel stages": ("blind",),
    "parallel review ones": ("blind",),
    "parallel review stages": ("blind",),
}

# Both patterns, each with the map that says which totals its nouns allow.
SWEEP_PATTERNS = ((COUNTED_PHRASE, COUNTED_NOUNS), (BLIND_PHRASE, BLIND_NOUNS))

# Files the sweep reads: every surface a user or another model is shipped.
#
# `.d2` is here because the diagram sources under docs/diagrams/ carry label
# text like "five blind" that a reader sees as a picture. The rendered SVGs are
# generated from those sources and are checked against them by
# tests/test_docs.py, so covering the source covers the picture.
SWEPT_SUFFIXES = (".md", ".mdc", ".json", ".d2")
SWEPT_SKIP_DIRS = {".git", "assets", "node_modules", "__pycache__"}

# Sentences that count a subset rather than a total. A subset count is a real
# fact that no derived number will ever match, so it is named here instead of
# being written around. Each entry is (path, the phrase the sweep sees).
COUNT_EXEMPT = {
    # Three of the seven parse the posting text directly. This is the reason the
    # capture has to be verbatim, and the number is the point of the sentence.
    ("skills/job-board-search/SKILL.md", "Three agents"),
    ("templates/job_description.md", "Three agents"),
    # The same subset, explained to a reader rather than to the model: it is
    # why the posting is captured verbatim instead of summarized.
    ("docs/architecture/pipeline.md", "Three agents"),
    ("docs/workspace.md", "Three agents"),
    # The same two sentences in each language. The mirror needs its own rows
    # because the exemption is keyed by the phrase the sweep sees, and that
    # phrase is written in the language of the file.
    ("translations/zh-CN/docs/architecture/pipeline.md", "3个智能体"),
    ("translations/zh-CN/docs/workspace.md", "3个智能体"),
    ("translations/es/docs/architecture/pipeline.md", "3 agentes"),
    ("translations/es/docs/workspace.md", "3 agentes"),
    ("translations/pt-BR/docs/architecture/pipeline.md", "3 agentes"),
    ("translations/pt-BR/docs/workspace.md", "3 agentes"),
    ("translations/vi/docs/architecture/pipeline.md", "3 tác nhân"),
    ("translations/vi/docs/workspace.md", "3 tác nhân"),
}

# --- translations ------------------------------------------------------------

# The reader-facing tree ships in English and four translations, mirrored under
# `translations/<tag>/` at the same paths the English tree uses. The mirror
# preserves path shape on purpose: a link between two translated pages is then
# byte-identical to the English link, so a translator never recomputes a path and
# the existing relative-link gate in tests/test_docs.py covers the mirror without
# knowing it exists.
#
# The set is four rather than five, and it is chosen for market fit rather than
# speaker count. This pipeline models anglophone hiring: `templates/resume.tex`
# prints a work-authorization block, `skills/application-builder/SKILL.md`
# enforces one page, and `agents/slushpile-ats-simulator.md` treats a photo as a
# parse failure. A manual in someone's language is an implicit promise the tool
# fits their market, and these four reach readers applying into the market it
# models. Japanese and Korean were dropped for the opposite reason rather than
# for lack of readers: those markets use a standardized form this pipeline would
# score as broken. Adding them needs the `market:` field, not a translator.


class Language(NamedTuple):
    tag: str  # the directory under translations/, and the BCP-47 tag
    label: str  # what the language nav prints, in that language


LANGUAGES = (
    Language("zh-CN", "简体中文"),
    Language("es", "Español"),
    Language("pt-BR", "Português (BR)"),
    Language("vi", "Tiếng Việt"),
)

ENGLISH_LABEL = "English"
MIRROR = "translations"

# Every page mirrored into every language. A page here without a file in every
# language directory is a generator error rather than a silent omission, on the
# same rule as a skill missing from SKILLS: a half-translated tree drops a reader
# into English mid-sentence and looks, in a diff, exactly like a finished one.
TRANSLATED = (
    "README.md",
    "INSTALL.md",
    "docs/index.md",
    "docs/getting-started.md",
    "docs/skills.md",
    "docs/workspace.md",
    "docs/voice.md",
    "docs/troubleshooting.md",
    "docs/architecture/index.md",
    "docs/architecture/pipeline.md",
    "docs/architecture/the-review.md",
    "docs/architecture/scoring.md",
    "docs/architecture/memory-and-calibration.md",
    "docs/architecture/agents-and-models.md",
    "docs/architecture/personal-data.md",
)

# Why every other tracked Markdown file is not translated, as ordered prefix
# rules. First match wins. tests/test_translations.py requires the rules to
# cover the tree exactly and requires every rule to match something, so a rule
# that stops applying is an error rather than dead weight — which is what keeps
# this from becoming a way to silently drop a page out of scope.
NOT_TRANSLATED = (
    (
        "skills/",
        "The product. These are prompts a model executes, not prose a person "
        "reads. Translating one changes what the model does, and there is no "
        "gate that could tell a good translation from a behaviour change.",
    ),
    (
        "agents/",
        "Same reason as skills/. An agent definition is executed, not read.",
    ),
    (
        "templates/",
        "Scaffolded into the user's own workspace and then edited by them. A "
        "translated copy would have to be chosen at onboarding time, which is "
        "the `market:` field's job, not a translation's.",
    ),
    (
        "docs/diagrams/",
        "D2 sources, their committed SVG renders, and the authoring guide. "
        "Translating a diagram means a per-language render pipeline and four "
        "more copies for the staleness gate to hold. Translated pages embed the "
        "English renders and translate the alt text instead.",
    ),
    (
        "docs/architecture/generated-surfaces.md",
        "Instructions for editing this repository. Every path it names points "
        "at CLAUDE.md and scripts/, which are not translated, so a translated "
        "copy would be a page whose every link leaves its own language.",
    ),
    (
        "docs/architecture/AGENTS.md",
        "Contributor guidance, and half of a byte-identical freeze pair. A "
        "translated twin would have to be frozen against a translated CLAUDE.md "
        "that does not exist.",
    ),
    (
        "docs/architecture/CLAUDE.md",
        "The other half of that pair, frozen byte-for-byte against it by "
        "tests/test_docs.py.",
    ),
    (
        "CLAUDE.md",
        "Repository standards, read by an agent working on this repository. "
        "Translating it would make a second source of truth for rules whose "
        "whole point is having one.",
    ),
    (
        "AGENTS.md",
        "Generated from CLAUDE.md and frozen against it, so translating it "
        "would fork a source of truth that exists to be single.",
    ),
    (
        "GEMINI.md",
        "The Gemini extension's context file: read by a model, not a person.",
    ),
    (
        "CONTRIBUTING.md",
        "Contributor-facing, and it sends the reader to CLAUDE.md and the gates, "
        "which are English.",
    ),
    (
        "NOTICE.md",
        "Licence attribution. The OFL text it points at is English, and a "
        "translated attribution is a legal claim nobody here can check.",
    ),
    (
        ".cursor/",
        "Generated router files a harness reads to find a skill. Machine "
        "surfaces, rebuilt from skills/ on every generator run.",
    ),
)

# Stated in every translated README and in none of the English pages, because the
# note exists for the reader the English pages do not have: someone who found
# this in their own language and has no reason to assume it models a hiring
# market other than their own. Generated rather than checked, so it cannot be
# dropped by a translator who did not know it was load bearing.
#
# The wording has to match the terminology each mirror settled on, and nothing
# checks that: this string lives in a script, so a pass that normalizes a
# language's vocabulary sweeps every page and leaves the one paragraph the
# generator writes.
MARKET_NOTE = {
    "zh-CN": (
        "> **适用范围**：本流水线针对英语国家（尤其是美国）的招聘惯例设计：简历一页、"
        "不放照片、不写出生日期、按时间倒序、并附上工作许可说明。若你投递的是使用"
        "标准化简历表格的本地岗位，其中的版式建议并不适用，审阅也会把本地惯例判为"
        "缺陷。相关讨论见 "
        "[issue #2](https://github.com/aaddrick/slushpile/issues/2)。"
    ),
    "es": (
        "> **Alcance**: este pipeline modela convenciones de contratación "
        "anglófonas, sobre todo estadounidenses: una página, sin foto, sin fecha "
        "de nacimiento, orden cronológico inverso y una línea de autorización de "
        "trabajo. Si postulas en un mercado local con otras convenciones, los "
        "consejos de formato no aplican y la revisión marcará como defectos "
        "cosas que allí son normales. Seguimiento en el "
        "[issue #2](https://github.com/aaddrick/slushpile/issues/2)."
    ),
    "pt-BR": (
        "> **Escopo**: este pipeline modela convenções de contratação "
        "anglófonas, principalmente dos EUA: uma página, sem foto, sem data de "
        "nascimento, ordem cronológica inversa e uma linha de autorização de "
        "trabalho. Se você se candidata em um mercado local com outras "
        "convenções, os conselhos de formatação não valem e a revisão vai "
        "apontar como defeito o que lá é normal. Acompanhe no "
        "[issue #2](https://github.com/aaddrick/slushpile/issues/2)."
    ),
    "vi": (
        "> **Phạm vi**: quy trình này mô phỏng quy ước tuyển dụng của các thị "
        "trường nói tiếng Anh, chủ yếu là Mỹ: một trang, không ảnh, không ngày "
        "sinh, sắp xếp ngược theo thời gian, và một dòng về tình trạng được phép "
        "làm việc. Nếu bạn ứng tuyển ở thị trường trong nước với quy ước khác, "
        "lời khuyên về định dạng không áp dụng và vòng đánh giá sẽ coi những gì "
        "bình thường ở đó là lỗi. Theo dõi tại "
        "[issue #2](https://github.com/aaddrick/slushpile/issues/2)."
    ),
}

# The counted nouns each language uses, and which derived total each one allows.
# Mirrors COUNTED_NOUNS above, in four more languages.
#
# Translated prose writes a derived count as a digit followed by one of these
# nouns. That is a real editorial constraint rather than a preference: the sweep
# above matches English number words, so 「九个技能」 would sail past it, and a
# count nobody checks is exactly the failure this repository already shipped
# three times in English. Digits plus a fixed noun make the count matchable
# without a number-word list per language.
#
# "personas" is deliberately not carried into Spanish or Portuguese, where the
# word means "people" and would match ordinary prose.
TRANSLATED_COUNTED_NOUNS = {
    "zh-CN": {
        "个技能": ("skills",),
        "个智能体": ("dispatch", "shipped"),
        "个智能体定义": ("shipped",),
        "个审阅者": ("dispatch",),
        "个角色": ("dispatch",),
        "个并行审阅者": ("blind",),
    },
    "es": {
        "habilidades": ("skills",),
        "agentes": ("dispatch", "shipped"),
        "definiciones de agente": ("shipped",),
        "revisores": ("dispatch",),
        "revisores en paralelo": ("blind",),
    },
    "pt-BR": {
        "habilidades": ("skills",),
        "agentes": ("dispatch", "shipped"),
        "definições de agente": ("shipped",),
        "revisores": ("dispatch",),
        "revisores em paralelo": ("blind",),
    },
    "vi": {
        "kỹ năng": ("skills",),
        "tác nhân": ("dispatch", "shipped"),
        "định nghĩa tác nhân": ("shipped",),
        "người đánh giá": ("dispatch",),
        "người đánh giá song song": ("blind",),
    },
}


def translated_phrase(nouns: dict[str, tuple[str, ...]]) -> re.Pattern[str]:
    r"""A digit-plus-noun pattern for one language's counted nouns.

    Longest noun first, so "revisores en paralelo" is not matched as "revisores"
    and then checked against the wrong total — which is not a missed match but a
    wrong one, failing against a number the sentence never claimed.

    A multi-word noun is escaped word by word and rejoined on `\s+`, for the
    same reason COUNTED_PHRASE does it: these files are hard-wrapped, so
    "5 revisores en\nparalelo" is ordinary prose. Escaping per word rather than
    substituting afterwards is not a style choice: `re.escape` escapes a space to
    `\ `, so replacing `" "` in its output lands inside that pair and leaves a
    literal backslash in the pattern, which matches nothing and reports a
    shortfall whose cause the translator cannot see.
    """
    ordered = sorted(nouns, key=len, reverse=True)
    return re.compile(
        r"(\d{1,2})\s*("
        + "|".join(
            r"\s+".join(re.escape(word) for word in noun.split())
            for noun in ordered
        )
        + r")",
    )


CURSOR_SKILL_FRONTMATTER = """---
name: slushpile
description: 'An adversarial job search that gets better as it goes. Set up a job-search workspace, search a careers board and score roles against the realistic applicant pool, build a resume and cover letter, review them with seven agents that return a verdict per submission channel, then write what the review finds back into the profile. Invoke with /slushpile and name what you want to do.'
disable-model-invocation: true
license: MIT
---
"""

CURSOR_RULE_FRONTMATTER = """---
description: 'Adversarial job search: pool-anchored fit scoring, adversarial review, channel-conditional verdicts, findings written back to the profile.'
alwaysApply: false
---
"""


# --- reading the tree --------------------------------------------------------


def spell(count: int) -> str:
    return NUMBER_WORDS.get(count, str(count))


ORDINALS = {7: "seventh", 8: "eighth", 9: "ninth"}


def plain(agent: str) -> str:
    """The agent's name without its namespace prefix, lowercase."""
    return agent.removeprefix("slushpile-").replace("-", " ")


def agent_model(name: str) -> str | None:
    """The `model` an agent's frontmatter declares, or None if it declares none."""
    block = FRONTMATTER_BLOCK.match(
        (ROOT / "agents" / f"{name}.md").read_text(encoding="utf-8")
    )
    if not block:
        return None
    found = MODEL_FIELD.search(block.group(1))
    return found.group(1) if found else None


def display(agent: str) -> str:
    return AGENT_DISPLAY.get(agent, plain(agent))


def titled(agent: str) -> str:
    """Display name with a leading capital, leaving an initialism alone."""
    name = display(agent)
    return name[0].upper() + name[1:]


def require_exact(declared: list[str], found: set[str], label: str) -> None:
    """Fail unless the declared list names every item on disk, once each.

    This is the check that makes the whole generator worth having. Without it, a
    skill added to `skills/` and not added here disappears from the router, the
    README, and the Gemini context file, and nothing reports it.
    """
    seen: set[str] = set()
    repeated: set[str] = set()
    for name in declared:
        if name in seen:
            repeated.add(name)
        seen.add(name)

    problems = []
    if missing := sorted(found - seen):
        problems.append(f"on disk but not listed: {', '.join(missing)}")
    if unknown := sorted(seen - found):
        problems.append(f"listed but not on disk: {', '.join(unknown)}")
    if repeated:
        problems.append(f"listed twice: {', '.join(sorted(repeated))}")
    if problems:
        raise ValueError(f"{label}: " + "; ".join(problems))


class Facts:
    """Everything the generated files claim, read from where it is true."""

    def __init__(self) -> None:
        on_disk = {p.parent.name for p in (ROOT / "skills").glob("*/SKILL.md")}
        if not on_disk:
            raise ValueError("skills/: no SKILL.md files found")

        self.agents = sorted(p.stem for p in (ROOT / "agents").glob("*.md"))
        if not self.agents:
            raise ValueError("agents/: no agent definitions found")

        self.dispatch, self.blind, self.sequential = self._read_dispatch()

        # Whatever is defined but not dispatched by the review is a voice agent:
        # generated per person, named after its author, listed last.
        self.voice = [name for name in self.agents if name not in set(self.dispatch)]
        if not self.voice:
            raise ValueError("agents/: no voice agent, so no skill can draft prose")

        require_exact(
            [skill.name for skill in SKILLS], on_disk, "SKILLS in scripts/sync_docs.py"
        )
        require_exact(
            list(REVIEWERS), set(self.dispatch), "REVIEWERS in scripts/sync_docs.py"
        )
        self.skills = SKILLS
        self.spine, self.called, self.anytime, self.caller = self._read_call_graph()

    def _read_call_graph(self) -> tuple[list[Skill], list[Skill], list[Skill], str]:
        """Split the skills into the spine, what the spine calls, and the rest.

        The README separates the commands a user types from the ones a pipeline
        stage dispatches for them, because a reader who thinks all seven are
        theirs to run will run the review by hand after the builder already ran
        it twice.

        Every declared edge is verified against the caller's SKILL.md. That is
        the check worth having: delete the humanize step from the builder and
        this fails, instead of leaving the README promising a call that no
        longer happens.
        """
        declared = {skill.name for skill in SKILLS}
        callers: dict[str, list[str]] = {}
        for skill in SKILLS:
            if not skill.runs:
                continue
            body = (ROOT / "skills" / skill.name / "SKILL.md").read_text(encoding="utf-8")
            for target in skill.runs:
                if target == skill.name:
                    raise ValueError(f"SKILLS: {skill.name} lists itself in runs")
                if target not in declared:
                    raise ValueError(
                        f"SKILLS: {skill.name} runs {target}, which is not a declared skill"
                    )
                if f"/slushpile:{target}" not in body:
                    raise ValueError(
                        f"skills/{skill.name}/SKILL.md: SKILLS says it runs {target}, "
                        f"but the file never invokes /slushpile:{target}. Either the "
                        f"call was removed and `runs` did not follow, or it never "
                        f"existed."
                    )
                callers.setdefault(target, []).append(skill.name)

        called = [skill for skill in SKILLS if skill.name in callers]
        anytime = [skill for skill in SKILLS if skill.anytime]
        spine = [
            skill for skill in SKILLS if skill.name not in callers and not skill.anytime
        ]

        if overlap := sorted(skill.name for skill in anytime if skill.name in callers):
            raise ValueError(
                f"SKILLS: {', '.join(overlap)} is both called by another skill and "
                f"flagged anytime. A skill belongs to exactly one README group."
            )
        if not spine:
            raise ValueError("SKILLS: every skill is called or anytime, leaving no spine")
        if not called:
            raise ValueError(
                "SKILLS: no skill declares `runs`, so the README has nothing to "
                "separate the spine from"
            )

        # The generated prose names one caller and says it dispatches all of
        # them. Two callers would need a sentence this script does not know how
        # to write, so it fails here rather than naming one and hiding the other.
        named = sorted({name for names in callers.values() for name in names})
        if len(named) != 1:
            raise ValueError(
                f"SKILLS: {', '.join(named)} all dispatch other skills, but the "
                f"README prose is written for exactly one caller. Update "
                f"readme_pipeline() to describe the new shape."
            )
        return spine, called, anytime, named[0]

    def _read_dispatch(self) -> tuple[list[str], list[str], list[str]]:
        path = ROOT / DISPATCH_SOURCE
        rows = []
        for line in path.read_text(encoding="utf-8").splitlines():
            match = DISPATCH_ROW.match(line.strip())
            if match:
                rows.append(
                    (
                        int(match.group(1)),
                        match.group(2),
                        match.group(3).strip(),
                        match.group(4).strip(),
                    )
                )
        if not rows:
            raise ValueError(f"{DISPATCH_SOURCE}: no `| N | `slushpile-*` |` dispatch rows")

        numbers = [number for number, _, _, _ in rows]
        if numbers != list(range(1, len(rows) + 1)):
            raise ValueError(
                f"{DISPATCH_SOURCE}: dispatch numbering is {numbers}, not 1..{len(rows)}"
            )

        defined = {p.stem for p in (ROOT / "agents").glob("*.md")}
        if undefined := [name for _, name, _, _ in rows if name not in defined]:
            raise ValueError(
                f"{DISPATCH_SOURCE}: dispatches {', '.join(undefined)}, "
                f"which have no definition"
            )

        # The Model column was captured and discarded for as long as it has
        # existed, which made it the one fact in this table nothing checked.
        mismatched = [
            f"{name} (table: {model or 'blank'}, definition: {agent_model(name) or 'none'})"
            for _, name, model, _ in rows
            if agent_model(name) != model
        ]
        if mismatched:
            raise ValueError(
                f"{DISPATCH_SOURCE}: the Model column disagrees with the agent "
                f"definitions it names — {'; '.join(mismatched)}. The frontmatter "
                f"is what a harness dispatches on; the column is documentation of "
                f"it. Change whichever one is wrong."
            )

        order = [name for _, name, _, _ in rows]
        blind = [name for _, name, _, stage in rows if stage == "parallel"]
        sequential = [name for _, name, _, stage in rows if stage != "parallel"]
        if not blind:
            raise ValueError(f"{DISPATCH_SOURCE}: no dispatch row runs in parallel")
        # The generated prose names the two later stages by role. Two is the
        # pipeline's shape today; a third would need sentences this script does
        # not know how to write, so it fails here rather than describing a
        # pipeline that no longer exists.
        if len(sequential) != 2:
            raise ValueError(
                f"{DISPATCH_SOURCE}: {len(sequential)} rows run after the blind stage, "
                f"but the generated prose is written for exactly 2. Update "
                f"build_cursor_skill() and the README reviewers region to describe "
                f"the new shape."
            )
        return order, blind, sequential

    @property
    def labels(self) -> dict[str, str]:
        agents, blind, skills = len(self.dispatch), len(self.blind), len(SKILLS)
        return {
            "agents": spell(agents),
            "Agents": spell(agents).capitalize(),
            "blind": spell(blind),
            "Blind": spell(blind).capitalize(),
            "skills": spell(skills),
            "Skills": spell(skills).capitalize(),
            # Every agent shipped, which is the dispatched personas plus the
            # voice agent. Prose about the product counts these; prose about the
            # review counts {agents}.
            "defined": spell(len(self.agents)),
            "Defined": spell(len(self.agents)).capitalize(),
            # The voice agent brings the shipped total one past the dispatched
            # seven, which is how the README introduces it.
            "ordinal_agents": ORDINALS.get(len(self.agents), f"{len(self.agents)}th"),
        }

    def label(self, text: str) -> str:
        return text.format(**self.labels)


def fill(text: str) -> str:
    """Reflow a paragraph to the width the hand-written files use."""
    return textwrap.fill(
        " ".join(text.split()), width=80, break_long_words=False, break_on_hyphens=False
    )


# --- mirrors -----------------------------------------------------------------


def build_agents_md(facts: Facts, sources: dict[str, str]) -> str:
    """AGENTS.md is CLAUDE.md with a generated-file header.

    The content is identical on purpose. A harness reading AGENTS.md needs the
    same standards as one reading CLAUDE.md, and any divergence between them is
    a bug rather than a feature worth supporting.
    """
    claude_md = sources["CLAUDE.md"]
    lines = claude_md.splitlines()

    # Keep the H1 first so the file still reads as a document, then insert the
    # marker directly beneath it.
    if lines and lines[0].startswith("# "):
        head, rest = lines[0], lines[1:]
        body = "\n".join(rest).lstrip("\n")
        return f"{head}\n\n{MARKER}\n\n{body}\n"

    return f"{MARKER}\n\n{claude_md}"


# --- the Cursor router -------------------------------------------------------


def table(header: tuple[str, str], rows: list[tuple[str, str]]) -> str:
    body = [f"| {left} | {right} |" for left, right in rows]
    return "\n".join([f"| {header[0]} | {header[1]} |", "|---|---|"] + body)


def build_cursor_skill(facts: Facts, sources: dict[str, str]) -> str:
    """The Cursor skill: a router, plus what changes when there are no subagents."""
    rows = [
        (facts.label(skill.cursor), f"`.slushpile/skills/{skill.name}/SKILL.md`")
        for skill in facts.skills
    ]

    blocks = [
        MARKER,
        "# Slushpile",
        fill(
            f"A job application pipeline. This skill is a router: the pipeline "
            f"itself lives in {spell(len(facts.skills))} skill files and "
            f"{spell(len(facts.agents))} agent definitions under `.slushpile/`."
        ),
        fill(
            "Read the matching file in full and follow it. Do not work from this "
            "summary — the details are the product, and every rule in those files "
            "carries a failure mode that this page does not have room for."
        ),
        table(("The user wants to", "Read"), rows),
        "## Before anything else",
        fill(
            "Check for `preferences.yaml` in the working directory. If it is "
            "absent, the workspace has not been set up, and every other skill "
            "here depends on it. Run onboarding first."
        ),
        "## The review pipeline without subagents",
        fill(
            f"Cursor has no subagent dispatch. The review runs its "
            f"{spell(len(facts.dispatch))} personas sequentially in one context."
        ),
        fill(
            "Read each definition from `.slushpile/agents/`, adopt it, write its "
            "report out in full, then move to the next. The order is: "
            + ", ".join(display(name) for name in facts.dispatch)
            + "."
        ),
        fill(
            f"The first {spell(len(facts.blind))} are supposed to be blind to each "
            f"other. In a single context they are not, and a specialist that has "
            f"already read the triage verdict will drift toward agreeing with it. "
            f"Writing each report out completely before starting the next is what "
            f"limits the bleed. Do not skip that."
        ),
        fill(
            f"The {display(facts.sequential[0])} gets all "
            f"{spell(len(facts.blind))} specialist reports. The "
            f"{display(facts.sequential[1])} gets everything."
        ),
        "## The one rule that matters most",
        fill(
            "Nothing in the pipeline hardcodes a fact about the user. Every "
            "personal fact — compensation floor, relocation, work authorization, "
            "clearance, targeting — lives in `preferences.yaml`, and every factual "
            "claim about their career lives in `profile.md`. Read those. Never "
            "assume a fact about the user that is not in one of them, and never "
            "write one into an application that you cannot point to."
        ),
        "## What this never does",
        fill(
            "It does not submit anything. No skill here touches an application "
            "portal, an email, or a form. It writes files that the user reads and "
            "sends themselves."
        ),
    ]
    return CURSOR_SKILL_FRONTMATTER + "\n" + "\n\n".join(blocks) + "\n"


def build_cursor_rule(facts: Facts, sources: dict[str, str]) -> str:
    """The always-on Cursor rule: shorter than the skill, and deliberately so."""
    rows = [
        (facts.label(skill.rule), f"`.slushpile/skills/{skill.name}/SKILL.md`")
        for skill in facts.skills
        if skill.rule is not None
    ]

    blocks = [
        MARKER,
        "# slushpile",
        fill(
            "An adversarial job search lives under `.slushpile/` in this "
            "workspace. What the review finds gets written back into the profile, "
            "so it compounds across roles."
        ),
        fill(
            "When the user asks to set up a job search, search a careers board, "
            "assess a role, build an application, or review one before sending it, "
            "read the matching skill file and follow it in full:"
        ),
        table(("Task", "File"), rows),
        fill(
            "Agent personas for the review are in `.slushpile/agents/`. Workspace "
            "templates are in `.slushpile/templates/`."
        ),
        "Two standing rules:",
        fill(
            "**Read `preferences.yaml` and `profile.md` before making any claim "
            "about the user.** Nothing in the pipeline hardcodes a personal fact. "
            "If it is not in one of those files, it is not true about this user, "
            "and it does not go in an application."
        ),
        fill(
            "**Never submit anything.** This pipeline writes files. The user reads "
            "them and sends them."
        ),
    ]
    return CURSOR_RULE_FRONTMATTER + "\n" + "\n\n".join(blocks) + "\n"


# --- generated regions inside hand-written files -----------------------------


def gemini_skills(facts: Facts) -> str:
    return "\n".join(f"@./skills/{skill.name}/SKILL.md" for skill in facts.skills)


def gemini_agents(facts: Facts) -> str:
    lead = fill(
        f"The review pipeline dispatches {spell(len(facts.dispatch))} personas. On "
        f"a harness without subagent dispatch, adopt each definition in turn and "
        f"run them sequentially, writing each report out before starting the next."
    )
    imports = "\n".join(f"@./agents/{name}.md" for name in facts.dispatch + facts.voice)
    return f"{lead}\n\n{imports}"


def readme_pipeline(facts: Facts) -> str:
    """The command list, grouped by who types it.

    A renamed skill leaves a documented command that fails, so the commands are
    generated. The grouping is generated for a second reason: a flat list of
    {skills} commands reads as {skills} things the user has to run, and three of
    them are things the builder already ran. That misreading costs a user two
    redundant review passes before they work out which commands are theirs.

    One column width across every block. The groups sit under separate headings
    and still read as one list, so a blurb column that shifted between them
    would look like a formatting mistake.
    """
    column = max(len(f"/slushpile:{skill.name}") for skill in facts.skills) + 2

    def block(skills: list[Skill]) -> str:
        entries = []
        for skill in skills:
            lines = [facts.label(line) for line in skill.readme]
            command = f"/slushpile:{skill.name}".ljust(column)
            rest = [" " * column + line for line in lines[1:]]
            entries.append("\n".join([f"{command}{lines[0]}"] + rest))
        return "```\n" + "\n\n".join(entries) + "\n```"

    spine, called = spell(len(facts.spine)), spell(len(facts.called))

    return "\n\n".join(
        [
            "### The main pipeline",
            fill(
                f"{spine.capitalize()} commands, in order. A search runs on these "
                f"alone."
            ),
            block(facts.spine),
            f"### The {called} it runs for you",
            fill(
                f"`/slushpile:{facts.caller}` dispatches all {called} of these "
                f"itself, in the course of building an application. Run one "
                f"directly only to work on materials this pipeline did not build "
                f"— a resume written elsewhere, a letter drafted by hand."
            ),
            block(facts.called),
            "### Any time",
            block(facts.anytime),
        ]
    )


def readme_reviewers(facts: Facts) -> str:
    rows = [(f"**{titled(name)}**", REVIEWERS[name]) for name in facts.dispatch]
    manager, contrarian = (plain(name) for name in facts.sequential)
    blind = spell(len(facts.blind))

    return "\n\n".join(
        [
            f"### The {spell(len(facts.dispatch))} reviewers",
            table(("Agent", "Simulates"), rows),
            fill(
                f"The first {blind} run in parallel and cannot see each other's "
                f"work. The {manager} sees all {blind}. The {contrarian} sees "
                f"everything, including the {manager}, and can overrule it."
            ),
        ]
    )


def docs_agent_table(facts: Facts) -> str:
    """Dispatch order, the model each agent declares, and what it simulates.

    Three facts from three places: the order comes from the dispatch table in
    the review skill, the model from each agent's own frontmatter, and the blurb
    from REVIEWERS above. Hand-written in docs/ it would be a fourth place a
    renamed agent has to reach, and the one nothing checks.
    """
    rows = [
        f"| {number} | `{name}` | {agent_model(name) or '—'} | {REVIEWERS[name]} |"
        for number, name in enumerate(facts.dispatch, 1)
    ]
    note = fill(
        f"Plus the voice agent, `{facts.voice[0]}`, which the review never "
        f"dispatches and which is named in `preferences.yaml` rather than here. "
        f"The first {spell(len(facts.blind))} run in parallel and are blind to "
        f"each other; the last two run in order."
    )
    return "\n".join(
        ["| # | Agent | Model | Simulates |", "|---|---|---|---|", *rows]
    ) + "\n\n" + note


def install_snippet(facts: Facts) -> str:
    """The block INSTALL.md tells a user to paste into their own AGENTS.md.

    The markers stay outside the fence. A reader copies the fenced block, and a
    generator marker pasted into their standing instructions would be noise they
    have no way to interpret.
    """
    bullets = "\n".join(
        f"- `~/.slushpile/skills/{skill.name}/SKILL.md` — {facts.label(skill.install)}"
        for skill in facts.skills
    )
    voice = facts.voice[0]

    body = "\n\n".join(
        [
            "## slushpile",
            fill(
                "A job application pipeline lives at `~/.slushpile`. When the user "
                "asks to set up a job search, search a careers board, build an "
                "application, or review one, read the matching skill and follow it:"
            ),
            bullets,
            fill(
                "The review dispatches personas defined in `~/.slushpile/agents/`. "
                "If you cannot dispatch subagents, adopt each definition in turn "
                "and run them sequentially, writing each report out before "
                "starting the next."
            ),
            fill(
                f"Cover letters are written by the voice agent named in "
                f"`preferences.yaml` under `voice.agent`. A working example ships "
                f"as `{voice}`; it is the plugin author's voice, and users generate "
                f"their own with "
                f"https://github.com/aaddrick/written-voice-replication"
            ),
            "Workspace templates are in `~/.slushpile/templates/`.",
        ]
    )
    return f"```markdown\n{body}\n```"


# --- the language nav --------------------------------------------------------


def page_path(relative: str, lang: str | None) -> str:
    """Where one page lives: the English tree, or a language's mirror of it."""
    return relative if lang is None else f"{MIRROR}/{lang}/{relative}"


def language_nav(relative: str, lang: str | None) -> str:
    """The language switcher for one page, rendered for one language.

    Generated rather than hand-written because there are seventy-five of these —
    fifteen pages across the English tree and four mirrors — and each carries
    four links whose relative depth differs by directory. A wrong path here is
    invisible until a reader clicks it, and a missing nav is invisible entirely.
    """
    here = posixpath.dirname(page_path(relative, lang)) or "."
    entries = []
    for tag, label in ((None, ENGLISH_LABEL), *((l.tag, l.label) for l in LANGUAGES)):
        if tag == lang:
            entries.append(f"  <strong>{label}</strong>")
        else:
            entries.append(
                f'  <a href="{posixpath.relpath(page_path(relative, tag), here)}">'
                f"{label}</a>"
            )
    return '<p align="center">\n' + " ·\n".join(entries) + "\n</p>"


# Hand-written file -> {region name: builder}. Everything between a region's
# markers is owned by this script.
REGIONS: dict[str, dict[str, Callable[[Facts], str]]] = {
    "GEMINI.md": {"skills": gemini_skills, "agents": gemini_agents},
    "README.md": {"pipeline": readme_pipeline, "reviewers": readme_reviewers},
    "INSTALL.md": {"harness-snippet": install_snippet},
    "docs/architecture/agents-and-models.md": {"agent-table": docs_agent_table},
}


# A directory's AGENTS.md, written as a byte-identical copy of its CLAUDE.md
# sibling, so an agent finds the same guidance under whichever name its harness
# looks for. tests/test_docs.py checks the pairs for equality independently, and
# finds them by scanning rather than from this table, so a pair added here
# without a generator run fails there too.
#
# The repository root is deliberately not in this table. Its AGENTS.md is built
# by build_agents_md, which stamps a provenance header, so the two differ by
# design and equality would be the wrong check.
TWINS: dict[str, str] = {
    "docs/architecture/AGENTS.md": "docs/architecture/CLAUDE.md",
    "docs/diagrams/AGENTS.md": "docs/diagrams/CLAUDE.md",
}


def region_plan(facts: Facts) -> dict[str, dict[str, str]]:
    """Every file with generated regions -> {region: rendered text}.

    Built rather than declared because the translated copies are the same
    regions at seventy-five addresses. Declaring them would mean a table that
    has to be edited every time a page or a language is added, which is the
    table this one exists to avoid.
    """
    plan: dict[str, dict[str, str]] = {}
    for target, regions in REGIONS.items():
        plan.setdefault(target, {}).update(
            {region: builder(facts) for region, builder in regions.items()}
        )

    for relative in TRANSLATED:
        plan.setdefault(relative, {})["language-nav"] = language_nav(relative, None)
        english = REGIONS.get(relative, {})
        for language in LANGUAGES:
            entry = plan.setdefault(page_path(relative, language.tag), {})
            entry["language-nav"] = language_nav(relative, language.tag)
            # A translated copy carries the English block verbatim. Skill names
            # and slash commands are literal strings a user types, so there is
            # nothing in these tables to translate, and a per-language rendering
            # would make every new skill block on four translations before the
            # generator could run.
            for region, builder in english.items():
                entry[region] = builder(facts)
            if relative == "README.md":
                entry["market-note"] = MARKET_NOTE[language.tag]
    return plan


def replace_region(text: str, region: str, rendered: str, target: str) -> str:
    """Return `text` with the marked region's contents replaced by `rendered`.

    Both markers must already exist. A region that has to install itself would
    have to guess where it ends, and guessing wrong silently eats hand-written
    prose on either side.
    """
    head, tail = begin(region), end(region)
    start = text.find(head)
    if start == -1:
        raise ValueError(f"{target}: no '{head}' marker")
    stop = text.find(tail, start)
    if stop == -1:
        raise ValueError(f"{target}: '{head}' is never closed by '{tail}'")
    return f"{text[: start + len(head)]}\n\n{rendered}\n\n{text[stop:]}"


# --- count claims ------------------------------------------------------------


def check_count_claims(facts: Facts) -> list[str]:
    """Verify the prose sentences that state a derived number.

    These are checked rather than generated because wrapping a single sentence in
    generator markers costs more readability than it buys. The cost is that
    rewording one means editing COUNT_CLAIMS, and the error below says so.
    """
    problems = []
    for target, template in COUNT_CLAIMS:
        wanted = facts.label(template)
        text = (ROOT / target).read_text(encoding="utf-8")
        if wanted not in text:
            shown = wanted.replace("\n", " ")
            problems.append(
                f"::error file={target}::does not contain the counted claim "
                f"{shown!r}. Either the count changed and the sentence did not, or "
                f"the sentence was reworded and COUNT_CLAIMS in "
                f"scripts/sync_docs.py needs the new wording."
            )
    return problems


def check_command_rosters(facts: Facts) -> list[str]:
    """Every skill appears as a command in every hand-written roster.

    The generator raises when a skill is missing from SKILLS. It cannot raise on
    a file it does not build, and the two surfaces that enumerate the skills in
    prose are exactly the two that each dropped a different one.
    """
    problems = []
    for target in COMMAND_ROSTERS:
        text = (ROOT / target).read_text(encoding="utf-8")
        missing = [s.name for s in facts.skills if f"/slushpile:{s.name}" not in text]
        if missing:
            problems.append(
                f"::error file={target}::never names {', '.join(missing)}. A skill "
                f"missing from a hand-written roster is a stage the reader of that "
                f"file cannot reach. Add it, or drop the file from COMMAND_ROSTERS "
                f"in scripts/sync_docs.py and record why."
            )
    return problems


def swept_files() -> list[Path]:
    """Every shipped surface the sweep reads, in a stable order."""
    found = []
    for path in sorted(ROOT.rglob("*")):
        if path.suffix not in SWEPT_SUFFIXES or not path.is_file():
            continue
        if SWEPT_SKIP_DIRS & set(path.relative_to(ROOT).parts):
            continue
        found.append(path)
    return found


def check_stray_counts(facts: Facts) -> list[str]:
    """Read every shipped surface for a counted noun and check the number.

    COUNT_CLAIMS only covers a sentence someone registered, so it cannot fail on
    a sentence nobody thought about. That is how "eight skills" survived in three
    files past the ninth skill shipping. This reads the tree instead: any counted
    noun anywhere has to carry a number that is currently true.

    A subset count ("three agents parse this text") is a real sentence that no
    total will match. Those are listed in COUNT_EXEMPT rather than reworded,
    because the number is what the sentence is for.
    """
    truths = {
        "skills": len(SKILLS),
        "dispatch": len(facts.dispatch),
        "shipped": len(facts.agents),
        "blind": len(facts.blind),
    }
    spellings = {word: value for value, word in NUMBER_WORDS.items()}

    problems = []
    for path in swept_files():
        target = path.relative_to(ROOT).as_posix()
        # The mirror is swept by check_translated_counts, which knows which
        # language each file is in. Sweeping it here as well would apply English
        # number words to prose that does not use them: a silent pass, which is
        # worse than no check because it looks like one.
        if target.startswith(f"{MIRROR}/"):
            continue
        text = path.read_text(encoding="utf-8")
        for pattern, nouns in SWEEP_PATTERNS:
            for match in pattern.finditer(text):
                word = match.group(1).lower()
                # A hard wrap can land inside either group, so both are
                # normalized before they are looked up or reported.
                noun = " ".join(match.group(2).lower().split())
                phrase = " ".join(match.group(0).split())
                if (target, phrase) in COUNT_EXEMPT:
                    continue
                allowed = {truths[kind] for kind in nouns[noun]}
                if spellings[word] in allowed:
                    continue
                line = text.count("\n", 0, match.start()) + 1
                wanted = " or ".join(NUMBER_WORDS[n] for n in sorted(allowed))
                problems.append(
                    f"::error file={target},line={line}::says {phrase!r}, but "
                    f"there are {wanted}. Fix the sentence, or if it counts a "
                    f"subset on purpose, add it to COUNT_EXEMPT in "
                    f"scripts/sync_docs.py."
                )
    return problems


GENERATED_REGION = re.compile(
    r"<!-- BEGIN GENERATED \S+: scripts/sync_docs\.py -->.*?<!-- END GENERATED \S+ -->",
    re.DOTALL,
)


def without_generated_regions(text: str) -> str:
    """Drop every marked region, preserving line count.

    Used when comparing an English page against its translations. A translated
    copy carries these blocks in English verbatim, so counting the English
    numbers inside them would demand translated equivalents that must not exist.
    """
    return GENERATED_REGION.sub(
        lambda match: "\n" * match.group(0).count("\n"), text
    )


def check_translated_counts(facts: Facts) -> list[str]:
    """The count sweep again, per language, plus a parity rule.

    Two failures, and the second is the one worth the extra pass. The first is a
    translated count that is simply wrong. The second is a translated count that
    vanished: a translator who renders "nine skills" as prose without a number,
    or drops the sentence, leaves nothing for any pattern to match, and a sweep
    that matches nothing reports success. So every translated page must carry at
    least as many counted phrases as the English page it mirrors. That is the
    rule that makes the per-language noun tables honest instead of decorative.
    """
    truths = {
        "skills": len(SKILLS),
        "dispatch": len(facts.dispatch),
        "shipped": len(facts.agents),
        "blind": len(facts.blind),
    }
    problems = []

    for relative in TRANSLATED:
        english = without_generated_regions(
            (ROOT / relative).read_text(encoding="utf-8")
        )
        expected = sum(
            len(pattern.findall(english)) for pattern, _ in SWEEP_PATTERNS
        )

        for language in LANGUAGES:
            nouns = TRANSLATED_COUNTED_NOUNS[language.tag]
            target = page_path(relative, language.tag)
            path = ROOT / target
            if not path.exists():
                continue  # generate() already fails on this, and says more.
            text = path.read_text(encoding="utf-8")

            found = 0
            for match in translated_phrase(nouns).finditer(text):
                found += 1
                # Both groups are whitespace-normalized before use. A hard wrap
                # can land inside a multi-word noun, and looking the raw capture
                # up would raise rather than fail: the sweep would abort on the
                # first wrapped noun and report nothing about any file, which
                # reads as a clean run right up until someone notices it never
                # printed a count.
                phrase = " ".join(match.group(0).split())
                noun = " ".join(match.group(2).split())
                if (target, phrase) in COUNT_EXEMPT:
                    continue
                allowed = {truths[kind] for kind in nouns[noun]}
                if int(match.group(1)) in allowed:
                    continue
                line = text.count("\n", 0, match.start()) + 1
                problems.append(
                    f"::error file={target},line={line}::says {phrase!r}, but "
                    f"there are {' or '.join(str(n) for n in sorted(allowed))}. "
                    f"Fix the sentence, or if it counts a subset on purpose, add "
                    f"it to COUNT_EXEMPT in scripts/sync_docs.py."
                )

            if found < expected:
                problems.append(
                    f"::error file={target}::carries {found} counted phrase(s) "
                    f"where {relative} carries {expected}. A count that survives "
                    f"translation as prose without a digit is a count nothing "
                    f"checks. Write every derived number as a digit followed by "
                    f"one of the nouns registered for {language.tag} in "
                    f"TRANSLATED_COUNTED_NOUNS."
                )

    return problems


# --- targets -----------------------------------------------------------------

# Derived file -> the builder that produces its whole content. This table exists
# so --check and the writer cannot disagree about which files are generated.
BUILDERS: dict[str, Callable[[Facts, dict[str, str]], str]] = {
    "AGENTS.md": build_agents_md,
    ".cursor/skills/slushpile/SKILL.md": build_cursor_skill,
    ".cursor/rules/slushpile.mdc": build_cursor_rule,
}


def generate() -> dict[str, str]:
    """Return {relative path: wanted content} for every generated file."""
    facts = Facts()
    wanted: dict[str, str] = {}

    # Regions first. A whole-file builder may mirror a file that has regions in
    # it, and mirroring the pre-generation text would ship a stale copy.
    for target, regions in region_plan(facts).items():
        path = ROOT / target
        if not path.exists():
            raise ValueError(
                f"{target}: does not exist. Every page in TRANSLATED needs a "
                f"file under {MIRROR}/<tag>/ for every language in LANGUAGES. A "
                f"half-translated tree drops a reader into English mid-sentence "
                f"and looks, in a diff, exactly like a finished one."
            )
        text = path.read_text(encoding="utf-8")
        for region, rendered in regions.items():
            text = replace_region(text, region, rendered, target)
        wanted[target] = text

    for twin, source in TWINS.items():
        wanted[twin] = (ROOT / source).read_text(encoding="utf-8")

    sources = {
        name: wanted.get(name) or (ROOT / name).read_text(encoding="utf-8")
        for name in ("CLAUDE.md",)
    }
    for target, builder in BUILDERS.items():
        wanted[target] = builder(facts, sources)

    return wanted


def check() -> int:
    try:
        wanted = generate()
        facts = Facts()
        problems = (
            check_count_claims(facts)
            + check_stray_counts(facts)
            + check_translated_counts(facts)
            + check_command_rosters(facts)
        )
    except ValueError as error:
        print(f"::error::{error}")
        print("\n1 problem(s) found.", file=sys.stderr)
        return 1

    for target, content in wanted.items():
        path = ROOT / target
        if not path.exists():
            problems.append(
                f"::error file={target}::missing. Run: python3 scripts/sync_docs.py"
            )
            continue
        if path.read_text(encoding="utf-8") != content:
            problems.append(
                f"::error file={target}::drifted from its source. "
                f"Run: python3 scripts/sync_docs.py"
            )

    if problems:
        for problem in problems:
            print(problem)
        print(f"\n{len(problems)} problem(s) found.", file=sys.stderr)
        return 1

    print(
        f"All {len(wanted)} generated documentation files and "
        f"{len(COUNT_CLAIMS)} counted claims match their sources. "
        f"Swept {len(swept_files())} files for a stale count, "
        f"{len(TRANSLATED) * len(LANGUAGES)} translated pages for a dropped one, "
        f"and {len(COMMAND_ROSTERS)} for a missing skill."
    )
    return 0


def write() -> int:
    try:
        wanted = generate()
    except ValueError as error:
        print(f"::error::{error}")
        return 1

    for target, content in wanted.items():
        path = ROOT / target
        before = path.read_text(encoding="utf-8") if path.exists() else None
        if before == content:
            print(f"unchanged  {target}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote      {target}")

    # Counts and rosters are prose, so they are reported rather than rewritten. A
    # writer that silently left them wrong would defeat the point of having them.
    facts = Facts()
    if problems := (
        check_count_claims(facts)
        + check_stray_counts(facts)
        + check_translated_counts(facts)
        + check_command_rosters(facts)
    ):
        for problem in problems:
            print(problem)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if a derived file has drifted, without writing anything",
    )
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
